server:
  port: ${PORT:3004}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/retargetdb}
    username: ${SPRING_DATASOURCE_USERNAME:retarget}
    password: ${SPRING_DATASOURCE_PASSWORD:retarget}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

# Kafka
featurestore:
  kafka:
    user-topic: ${FEATURESTORE_KAFKA_USER_TOPIC:user-events}
    order-topic: ${FEATURESTORE_KAFKA_ORDER_TOPIC:order-events}

spring:
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
