server:
  port: 3000

spring:
  application:
    name: recommend-api-service

# downstream services (change if needed)
feature:
  store:
    url: http://feature-store-service:3004

retrieval:
  url: http://retrieval-service:3005

ranking:
  url: http://ranking-service:3006

rl:
  offer:
    url: http://rl-offer-service:3007
